### ISSUE TITLE
turning on debug logging

### ISSUE THREAD

**Issue by pfps** [cvuchener/hidpp#22]
I'm the maintainer of Solaar, a mostly GUI-based tool to control HID++ devices.  I'm trying to find out why Solaar is not working with a particular device that works fine in hidpp.  I would  like to take a look at what hidpp is sending to the device and it appears that there is debugging code in hidpp.

However, I can't see how to turn it on.  Please let me know how to turn debugging logging on.  Thanks.

**Comment by cvuchener** [comment]
Use `-vdebug:report` (or just `-vdebug` for every kind of debug message). The syntax for the logging settings is described in the documentation of `Log::init`.
