### ISSUE TITLE
Report's answer comes as INTERRUPT, not as SET_REPORT response

### ISSUE THREAD

**Issue by qodroi** [cvuchener/hidpp#33]
I couldn't get the idea of it. I intercept the Wireshark packets of `hidpp20-call-function`, while the binary returns back the correct data, Wireshark returns an empty SET_REPORT response _and_ an INTERRUPT IN packet that contains the actual expected values.

How does `hidpp20-call-function` handles this behaviour?

Thanks!

**Comment by cvuchener** [comment]
Input and output reports are independent in HID protocol. The response is matched with the command by checking feature/function/softwareID from the HID++ data.
