### ISSUE TITLE
Unifying receiver stops working after a short while with Thunderbolt dock

### ISSUE THREAD

**Issue by cmericli** [cvuchener/hidpp#7]
The system is a Dell Precision 7730 running Ubuntu 18.04.1 with Dell TB18 Thunderbolt dock. When I plug the unifying receiver to the laptop directly, it works just fine. When plugged to a USB port on the TB18 dock, it works for about a minute and then stops working. Plug out / plug in yields the same result. Running usbhid-dump resurrects it briefly, it then stops working again. Nothing on dmesg. 

Same behavior on three identical setups. 

How can I chase this issue further?

**Comment by cvuchener** [comment]
What does "not working" mean? What are you trying to do?

**Comment by cmericli** [comment]
Well, I have a mouse (M705) and a keyboard (MK710) paired to that unified receiver, and they simply stop working as in when I move the mouse, it does not move and when I hit the keys on the keyboard, it doesn't type :)

**Comment by cvuchener** [comment]
If you are not using any software from this repository, you should report this bug to your distribution bug tracker (or to the kernel directly if you can reproduce it with a mainline kernel).

**Comment by cmericli** [comment]
OK I thought since you seem to be the maintainer of this driver, this would be more to the point. I will report it to Canonical then. Thank you very much.
